### PR TITLE
Php7 (mostly)

### PR DESCRIPTION
**Pull request by BrockleyJohn**
changes for php7 plus a couple of bugs and an improvement to get going more easily

bugfixes are in
WCFDataServicesEntity.php
ObjectContext.php

ease of use improvement in
PHPDataSvcUtil.php

### CODE REVIEW

**Review by hansfn — CHANGES_REQUESTED** [review]
In framework/PHPDataSvcUtil.php you make some changes that should be commented and there are some code style issues:

- Why do you need to set the include path? As a minimum leave a comment. ADDED: I think I understand why now: You didn't set it in php.ini as instructed in the readme. Since we need to edit the php.ini anyway, I think it makes sense to also set the include path :-)
- You are completely removing the "service path not set" exception. Why? Comment and consinder if it can should be added again some where.
- Changes at line 28 - indent and parenthesis. (Code style.)
- At line 220. Why is the closing pre outside the Exception? Shouldn't it be before the true argument?

**Comment by hansfn** [comment]
Thx a lot for the PR. PHP 7 support is very much wanted. (I haven't used this for a new project for a very long time.)

PS! "eponymous" constructor? It doesn't look like a likely typo so what it is?

**Comment by BrockleyJohn** [comment]
I was working on shared hosting: no straightforward access to command line or php ini. It's entirely possible that generating the proxy classes only needs to be done once (if to work against a pre-existing data store) and it's the only thing that's done from that directory. It's also the first thing you do when you acquire the framework so it seems nice to make it work out of the box.

I removed the service path not set exception because I hard-coded the path and thus it's impossible to throw it! Frankly, I couldn't find any way that it could be set - did some code get lost along the way? I had forgotten - I left it like that for further discussion

The closing pre in the exception is a typo that didn't affect the test result - corrected.

"Eponymous" is a bit of artiness creeping into coding and a little joke with myself. It is most often used in the context of music but you'll also hear it with books, plays, films and so on, eg.
The Clash's eponymous album is their first one: The Clash - The Clash, and there are many examples of this as it's common not to give a first album a proper title.
King Lear is the eponymous character giving his name to Shakespeare's play

So php4 classes have eponymous constructors - methods with the same name as the class

**Comment by BrockleyJohn** [comment]
sorry - that's the wrong style of bracketing - will revise

**Comment by hansfn** [comment]
Thx for the Eponymous explanation :-)

I noticed the wrong brace style, but wasn't going to complain. If you update, fix the indent of the next line too.

Regarding include path: Can't the code that uses the SDK set the include path (in the cases when you can't edit php.ini)?

**Comment by BrockleyJohn** [comment]
Yes the code using the SDK can - that's why there's a specific change in this once-only file which is not part of the using application - to cope with a solution other than changing php.ini without needing an implementation-specific solution.

**Review by hansfn — APPROVED** [review]

**Comment by hansfn** [comment]
Thx for your work. 

I'll make a new release when I'm confident it works smoothly for PHP7. Maybe you find some more bugs too ;-)

**Pull request merged**
